# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agriculture_pb2 as agriculture__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agriculture_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgricultureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAll = channel.unary_unary(
                '/agriculture.AgricultureService/ListAll',
                request_serializer=agriculture__pb2.Empty.SerializeToString,
                response_deserializer=agriculture__pb2.ProductList.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/agriculture.AgricultureService/GetById',
                request_serializer=agriculture__pb2.ProductIdRequest.SerializeToString,
                response_deserializer=agriculture__pb2.Product.FromString,
                _registered_method=True)
        self.GetByCategory = channel.unary_unary(
                '/agriculture.AgricultureService/GetByCategory',
                request_serializer=agriculture__pb2.CategoryRequest.SerializeToString,
                response_deserializer=agriculture__pb2.ProductList.FromString,
                _registered_method=True)
        self.XPathQuery = channel.unary_unary(
                '/agriculture.AgricultureService/XPathQuery',
                request_serializer=agriculture__pb2.XPathRequest.SerializeToString,
                response_deserializer=agriculture__pb2.XPathResponse.FromString,
                _registered_method=True)


class AgricultureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XPathQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgricultureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAll': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAll,
                    request_deserializer=agriculture__pb2.Empty.FromString,
                    response_serializer=agriculture__pb2.ProductList.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=agriculture__pb2.ProductIdRequest.FromString,
                    response_serializer=agriculture__pb2.Product.SerializeToString,
            ),
            'GetByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByCategory,
                    request_deserializer=agriculture__pb2.CategoryRequest.FromString,
                    response_serializer=agriculture__pb2.ProductList.SerializeToString,
            ),
            'XPathQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.XPathQuery,
                    request_deserializer=agriculture__pb2.XPathRequest.FromString,
                    response_serializer=agriculture__pb2.XPathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agriculture.AgricultureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agriculture.AgricultureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgricultureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agriculture.AgricultureService/ListAll',
            agriculture__pb2.Empty.SerializeToString,
            agriculture__pb2.ProductList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agriculture.AgricultureService/GetById',
            agriculture__pb2.ProductIdRequest.SerializeToString,
            agriculture__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agriculture.AgricultureService/GetByCategory',
            agriculture__pb2.CategoryRequest.SerializeToString,
            agriculture__pb2.ProductList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def XPathQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agriculture.AgricultureService/XPathQuery',
            agriculture__pb2.XPathRequest.SerializeToString,
            agriculture__pb2.XPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
