# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agriculture.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agriculture.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61griculture.proto\x12\x0b\x61griculture\"\x07\n\x05\x45mpty\"\x1e\n\x10ProductIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x0f\x43\x61tegoryRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\"\n\x0cXPathRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"\xd2\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cprice_per_kg\x18\x04 \x01(\x01\x12\x18\n\x10units_shipped_kg\x18\x05 \x01(\x05\x12\x15\n\runits_sold_kg\x18\x06 \x01(\x05\x12\x18\n\x10units_on_hand_kg\x18\x07 \x01(\x05\x12\x10\n\x08supplier\x18\x08 \x01(\t\x12\x15\n\rfarm_location\x18\t \x01(\t\x12\x11\n\tsale_date\x18\n \x01(\t\"5\n\x0bProductList\x12&\n\x08products\x18\x01 \x03(\x0b\x32\x14.agriculture.Product\" \n\rXPathResponse\x12\x0f\n\x07results\x18\x01 \x03(\t2\x9b\x02\n\x12\x41gricultureService\x12\x37\n\x07ListAll\x12\x12.agriculture.Empty\x1a\x18.agriculture.ProductList\x12>\n\x07GetById\x12\x1d.agriculture.ProductIdRequest\x1a\x14.agriculture.Product\x12G\n\rGetByCategory\x12\x1c.agriculture.CategoryRequest\x1a\x18.agriculture.ProductList\x12\x43\n\nXPathQuery\x12\x19.agriculture.XPathRequest\x1a\x1a.agriculture.XPathResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agriculture_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_PRODUCTIDREQUEST']._serialized_start=43
  _globals['_PRODUCTIDREQUEST']._serialized_end=73
  _globals['_CATEGORYREQUEST']._serialized_start=75
  _globals['_CATEGORYREQUEST']._serialized_end=110
  _globals['_XPATHREQUEST']._serialized_start=112
  _globals['_XPATHREQUEST']._serialized_end=146
  _globals['_PRODUCT']._serialized_start=149
  _globals['_PRODUCT']._serialized_end=359
  _globals['_PRODUCTLIST']._serialized_start=361
  _globals['_PRODUCTLIST']._serialized_end=414
  _globals['_XPATHRESPONSE']._serialized_start=416
  _globals['_XPATHRESPONSE']._serialized_end=448
  _globals['_AGRICULTURESERVICE']._serialized_start=451
  _globals['_AGRICULTURESERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
